runtime: python311
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

instance_class: F1

automatic_scaling:
  max_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5

env_variables:
  PYTHONUNBUFFERED: 'True'